$('.owl-carousel').owlCarousel({
    loop:true,
    margin:13,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        370:{
            items:3
        },
        600:{
            items:5
        },
        1000:{
            items:7
        }
    }
})